"use client";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import type { Summary } from "@ai-meeting-notes/shared";

interface SummaryPanelProps {
  summary: Summary | undefined;
  loading?: boolean;
}

/**
 * Summary + decisions + topic chips for the meeting detail page.
 *
 * Renders nothing for a missing summary (the pipeline-status strip
 * tells the user we're still summarizing). When `loading` is true,
 * shows skeletons sized roughly to what we expect from Claude.
 */
export function SummaryPanel({ summary, loading }: SummaryPanelProps) {
  if (loading && !summary) {
    return (
      <Card>
        <CardHeader className="border-b border-border py-4 px-5">
          <CardTitle className="card-title">Summary</CardTitle>
        </CardHeader>
        <CardContent className="p-5 space-y-3">
          <Skeleton className="h-4 w-full" />
          <Skeleton className="h-4 w-[92%]" />
          <Skeleton className="h-4 w-[70%]" />
        </CardContent>
      </Card>
    );
  }

  if (!summary) return null;

  return (
    <Card>
      <CardHeader className="border-b border-border py-4 px-5">
        <CardTitle className="card-title">Summary</CardTitle>
      </CardHeader>
      <CardContent className="p-5 space-y-4">
        <p className="text-sm leading-relaxed">{summary.summary}</p>

        {summary.decisions.length > 0 && (
          <section>
            <h3 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-2">
              Decisions
            </h3>
            <ul className="list-disc list-inside space-y-1 text-sm">
              {summary.decisions.map((d, i) => (
                <li key={i}>{d}</li>
              ))}
            </ul>
          </section>
        )}

        {summary.topics.length > 0 && (
          <section>
            <h3 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-2">
              Topics
            </h3>
            <div className="flex flex-wrap gap-1.5">
              {summary.topics.map((t) => (
                <span
                  key={t}
                  className="text-xs px-2 py-0.5 rounded-full border border-border bg-muted/40"
                >
                  {t}
                </span>
              ))}
            </div>
          </section>
        )}

        <p className="text-xs text-muted-foreground pt-2">
          Generated by {summary.model}
        </p>
      </CardContent>
    </Card>
  );
}
